### ISSUE TITLE
Error in AuditableObserver (v5.0)

### ISSUE THREAD

**Issue by Albvadi** [owen-it/laravel-auditing#354]
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | 5.5.22
| Package version   | 5.0.0
| PHP version       | 7.0.9

#### Actual Behaviour
Error trying to save a new instance of a audit model.

#### Steps to Reproduce
App\Company.php (Model)
```PHP
use OwenIt\Auditing\Contracts\Auditable;
class Company extends Model implements Auditable
{
    use SoftDeletes;
    use \OwenIt\Auditing\Auditable;

    ...
}
```
Route
```PHP
Route::get('/create_company', function () {
    dd((factory(App\Company::class)->create())->toArray());
});
```
Error:
![image](https://user-images.githubusercontent.com/6285255/33385438-eac78248-d528-11e7-86c0-3582f0d7c940.png)

**Comment by quetzyg** [comment]
You sure you're on PHP 7? The only time I had issues like that was with PHP 5.5.x/5.6.x, where I had to use an alias. PHP 7.x shoud be OK with using the same class name, as long as at least one is using the FQCN.

Anyways, try:
```php
use OwenIt\Auditing\Contracts\Auditable as AuditableContract;

class Company extends Model implements AuditableContract
{
    use SoftDeletes;
    use \OwenIt\Auditing\Auditable;

    ...
}
```

**Comment by quetzyg** [comment]
The [issue](https://bugs.php.net/bug.php?id=72159) was fixed in PHP 7.0.7.

**Comment by Albvadi** [comment]
Sure, my PHP version it´s 7.0.9. Load in a phpinfo() page inside laravel.

I followed your suggestion, but the problem persist.
Besides, I created and empty laravel installation, only just in case I had forgotten something in the upgrade from 4.1.4 and same problem.

In the new installation, with all default config:
App\User.php
```PHP
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use OwenIt\Auditing\Contracts\UserResolver;

class User extends Authenticatable implements UserResolver
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * {@inheritdoc}
     */
    public static function resolveId()
    {
        return Auth::check() ? Auth::user()->getAuthIdentifier() : null;
    }
}
```
App\Company.php
```PHP
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use OwenIt\Auditing\Contracts\Auditable;

class Company extends Model implements Auditable
{
    use \OwenIt\Auditing\Auditable;
}
```
routes\web.php
```PHP
Route::get('/company', function () {
    $company = new Company;
    $company->name = "TEST COMPANY";
    $company->save();
});
```

**Comment by quetzyg** [comment]
>I followed your suggestion, but the problem persist.

No you haven't, you're not using an alias, like I have in the example above.

**Comment by Albvadi** [comment]
Was a copy/paste problem... sorry.
But, tried with your suggestion... problem persist.

![image](https://user-images.githubusercontent.com/6285255/33426334-bde6116a-d5c1-11e7-8455-8db2a48e9cec.png)
![image](https://user-images.githubusercontent.com/6285255/33426366-d080c158-d5c1-11e7-8eb4-38f918607f12.png)

**Comment by Albvadi** [comment]
Besides, downgrade from 5.0.1 to 4.1.4, works perfect without touching my model setup

**Comment by quetzyg** [comment]
Any **4.1.x** version has the [alias](https://github.com/owen-it/laravel-auditing/blob/4.1/src/AuditableObserver.php#L17) set to prevent such issue, but like I said, this is a PHP 5.5.x/5.6.x and 7.0.0 to 7.0.7 problem.

These are the [PHP 5.5.21 and 5.6.5 builds failing](https://travis-ci.org/owen-it/laravel-auditing/builds/210086174) on Travis CI, exactly because of that. Once I [added](https://github.com/owen-it/laravel-auditing/pull/199/commits/b5283794b9c668c362711a662cdf2d0f947ddeea) aliases, the [tests passed](https://travis-ci.org/owen-it/laravel-auditing/builds/210088692).

The tests don't lie. 
#shakira

The issue you're having should not happen in the PHP version you say you have. So you either have multiple PHP versions and you think you're using one, instead of another, or the issue wasn't properly fixed in PHP 7.0.7 and you need a higher version.

Try upgrading to a more recent PHP version and see if the issue disappears.

Version 7.0.x [won't be actively supported](http://php.net/supported-versions.php) for much longer, anyway.

**Comment by Albvadi** [comment]
Upgraded PHP to 7.0.13 solve the issue without using alias.

I'm sorry I bothered you so much.
Maybe you should update the readme.md to avoid people like me.

Thanks for all your support!

**Comment by quetzyg** [comment]
Not a problem, I'll update the `composer.json` requirements and bump the PHP version to avoid similar issues.

**Comment by quetzyg** [comment]
I just checked the changelog for 7.0.13 and it does fix the [issue](http://bugs.php.net/66773).

**Comment by Albvadi** [comment]
I thought I was going crazy!!
Thanks for your research!
