### ISSUE TITLE
Official site is down?

### ISSUE THREAD

**Issue by threeFatCat** [owen-it/laravel-auditing#619]
I'm about to check the docs in the official site, but it turns out it's down. I was able to check it yesterday. 

![image](https://user-images.githubusercontent.com/11312281/97393109-0051b480-191e-11eb-985f-35dcb1d463bb.png)

**Comment by nathan-io** [comment]
This appears to be a recurring problem. See https://github.com/owen-it/laravel-auditing/issues/600.

Hope it's fixed soon...

**Comment by anteriovieira** [comment]
Fixed!

**Comment by mweikat** [comment]
Hi , what happens with the official site, will it not be enabled? error persists
